### ISSUE TITLE
Need to add quick xml to cargo toml in newest version

### ISSUE THREAD

**Issue by daniel-brenot** [ImJeremyHe/xmlserde#28]
Whe I use the XmlDeserialize macro, I need to make sure to add the quick_xml crate to my cargo.toml. Specifically version 0.29, as this crate doesn't work with the newest version.

I think a way around this would be to re-export quick_xml from your crate, and then make the use statement in your derive code refer to that version. That way someone could use a different version of quick xml in their code than what your crate uses.

Alternatively, it would be good to document in the readme that quick_xml needs to be added to your dependencies in order to use this crate.

Thanks for the great work, this reads much better than serde!

**Comment by ImJeremyHe** [comment]
Thank you @daniel-brenot! Sorry for the late reply. I will do that in the next update
