### ISSUE TITLE
Unwanted removal of spaces at the beginning and end of the text

### ISSUE THREAD

**Issue by Shohaii** [ImJeremyHe/xmlserde#43]
I see that [`reader.trim_text`](https://github.com/ImJeremyHe/xmlserde/blob/main/src/lib.rs#L343) is set to `false`,
but still when I deserialize following xml:
```
<text:p text:style-name="P2">
    <text:span text:style-name="T1">Warning:</text:span>
    <text:span text:style-name="T3"> missing spaces at the </text:span>
    <text:span text:style-name="T2">beginning</text:span>
    <text:span text:style-name="T3"> and </text:span>
    <text:span text:style-name="T2">end</text:span>
    <text:span text:style-name="T3"> of this sentence </text:span>
</text:p>
```

and serialize it again, I get:
```
<text:p text:style-name="P2">
    <text:span text:style-name="T1">Warning:</text:span>
    <text:span text:style-name="T3">missing spaces at the</text:span>
    <text:span text:style-name="T2">beginning</text:span>
    <text:span text:style-name="T3">and</text:span>
    <text:span text:style-name="T2">end</text:span>
    <text:span text:style-name="T3">of this sentence</text:span>
</text:p>
```

Am I missing some setting? How can I fix this, please?
If you think there is a bug in my data structures I can share them.

Note: This happens only with documents, created by LibreOffice/OpenOffice. MS Word uses `<text:s/>` instead of leading/trailing whitespaces so there is no problem.

**Comment by ImJeremyHe** [comment]
Thank you for your report. @Shohaii 
I think it might be the issue here
https://github.com/ImJeremyHe/xmlserde/blob/7579d5573c936b2f281b187eee357772694bc29d/derives/src/de.rs#L599

Can you confirm that if you are using a `ty=text` in an untag enum? If yes, this should be a simple fix. If no, it will take some time to do some investigation

**Comment by Shohaii** [comment]
Yes, my structs for deserialization are:
```
#[derive(Debug, XmlSerialize, XmlDeserialize)]
pub struct TextSpan {
    #[xmlserde(name = b"text:style-name", ty = "attr")]
    pub text_style_name: String,
    #[xmlserde(ty = "untag")]
    pub text_span_content: Vec<TextSpanContent>,
}

#[derive(Debug, XmlSerialize, XmlDeserialize)]
pub enum TextSpanContent {
    #[xmlserde(ty = "text")]
    Text(String),
    // other types
}
```

So it will be the first option.
